dos:
  image: democracyos/app:0.14.0-deis
  ports:
    - "8000:80"
  external_links:
    - debatics_mongo_1:mongo
  links:
    - notifier
  environment:
    - NODE_PATH=.
    - PORT=80
    - PROTOCOL=http
    - PUBLIC_PORT=80
    - STAFF=itpami@pami.org.ar
    - MONGO_URL=mongodb://mongo:27017/jefatura
    - HOST=gobiernoabierto.pami.org.ar
    - NODE_ENV=production
    - ORGANIZATION_NAME=Coordinación de Gobierno Abierto
    - ORGANIZATION_URL=http://www.gobiernoabierto.gob.ar
    - LOCALE=es
    - LOGO=/lib/boot/images/logo_ga.png
    - NOTIFICATIONS_URL=http://notifier:9002/api/events
    - NOTIFICATIONS_TOKEN=%NOTIFICATIONS_TOKEN%
    - DEBUG=democracyos*
    - JWT_SECRET=%JWT_SECRET%
    - LEARN_MORE_URL=http://www.gobiernoabierto.gob.ar/novedades/participa-del-ii-plan-de-accion-2015-2017-de-la-republica-argentina_n249

notifier:
  build: ./notifier
  ports:
    - "9002:9002"
  external_links:
    - debatics_mongo_1:mongo
  volumes:
    - ./notifier/app /app
