dos:
  image: democracyos/app:0.14.0-deis
  ports:
    - "8000:80"
  external_links:
    - debatics_mongo_1:mongo
    - debatics_notifier_1:notifier
  environment:
    - NODE_PATH=.
    - PORT=80
    - PROTOCOL=http
    - PUBLIC_PORT=80
    - STAFF=itpami@pami.org.ar
    - MONGO_URL=mongodb://mongo:27017/jefatura
    - HOST=gobiernoabierto.pami.org.ar
    - NODE_ENV=production
    - ORGANIZATION_NAME=Plan de Acción de Gobierno Abierto 2015-2017
    - ORGANIZATION_URL=http://www.gobiernoabierto.gob.ar
    - LOCALE=es
    - LOGO=/lib/boot/images/logo_ga.png
    - NOTIFICATIONS_URL=http://notifier:9001/api/events
    - NOTIFICATIONS_TOKEN=%NOTIFICATIONS_TOKEN%
    - DEBUG=democracyos*
    - JWT_SECRET=%JWT_SECRET%
